-- AlterTable
ALTER TABLE "Building" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Developer" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Floor" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Permission" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "latitude" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "longitude" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "startingPrice" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RolePermission" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "amenities" JSONB,
ADD COLUMN     "media" JSONB,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "area" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "basePrice" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
